### ISSUE TITLE
[BUG] Game Randomly Crashes

### ISSUE THREAD

**Issue by Memer56** [Mnesikos/SimplyCats#39]
**Describe the bug**
For some reason after not too long of using the mod, my game keeps crashing soon after logging onto my world and 
I receive the error: 

The game crashed whilst ticking entity
Error: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

**To Reproduce**
Unsure on how to reproduce the error, although I had used the summon command to spawn 3 cats.

**Expected behavior**
To let me have my cats :)

**Logs (REQUIRED)**
Due to amount of mods used I had to separate the pastbin's

Simply Cats Error Log: https://pastebin.com/tSBCZXT3
Simply Cats Latest Log: https://pastebin.com/q73KTavP 

**Screenshots**

**Versions (please complete the following information):**
 - Minecraft [1.20.1]
 - Forge [47.2.0]
 - Simply Cats [0.2.3]

**Additional context**
A whole host of other mods where used which can be seen in the reports, I have no idea if there's an underlying mod conflict but judging from the error it keeps pointing to this mod much to my dismay, good luck :)

**Comment by Mnesikos** [comment]
This is not a random crash nor a bug, you used the summon command incorrectly and got a broken cat.

**Comment by Memer56** [comment]
Unless the example command is wrong then where would it be wrong? Actually I used the spawn eggs first does that spawn broken cats?

Edit: Unless the kill command doesn't target broken cats too then this is a bug, the moment someone else joins my world it crashes, and all the crash reports point to this mod being the problem, if you know how to fix this situation great, if not, great I've just killed my cats for no reason. 

The fact that it's possible to spawn a broken cat that breaks my world like this to me is a bug. It begs the question, if an argument of the command is invalid then why doesn't the command return as invalid rather than allowing a broken entity in the world? I beg of you to address this issue.

Maybe it would be better to have some form of creative GUI for users to easily create custom cats because it appears to be just too easy to spawn a broken cat.

**Comment by Mnesikos** [comment]
The summon command is a vanilla command that does not inherently work with the way simply cats is made. I did what I could with what I have to make it work as far as it does, and it will not be further supported solely because I don't want to deal with it. End of story. Cats are intended to be random and I have no interest in using my very little free time to change that very specific design of my mod.

In order for this "bug" to be valid and for me to help figure it out, I would need an exact copy of the command you sent to spawn said broken cat; or if you can prove without a doubt it was a mod-generated cat that is broken then I would need the steps to reproduce it.

If you used the kill command while the chunk with the broken cat was loaded, and thus killed the broken cat, then I would need the new crash logs that are somehow still pointing to Simply Cats to deem this a Simply Cats bug.

PS if you are sending more logs, do not edit them. Send the entire log. The "Simply Cats Error Log" you shared seems to be missing the first half of its intended data.
